openapi: 3.0.0
paths:
  /search-simple/{from}/{to}/{depart}:
    get:
      operationId: AppController_getSearchSimple
      parameters:
        - name: return
          required: false
          in: query
          description: Return date of the flight in yyyy-mm-dd format
          schema:
            type: string
        - name: depart
          required: true
          in: path
          description: Depature date of the flight in yyyy-mm-dd format
          schema:
            type: string
        - name: to
          required: true
          in: path
          description: IATA location flight destination
          schema:
            type: string
        - name: from
          required: true
          in: path
          description: IATA location flight origin
          schema:
            type: string
      responses:
        '200':
          description: Creates a flight search
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Search'
info:
  title: Flights API
  description: Flights API search using skyscanner apis
  version: '1.0'
  contact: {}
tags: []
servers:
  - url: http://localhost:3000
components:
  schemas:
    DeepLink:
      type: object
      properties:
        link:
          type: string
        type:
          type: string
        agentImageUrl:
          type: string
        agentName:
          type: string
      required:
        - link
        - type
        - agentImageUrl
        - agentName
    Deal:
      type: object
      properties:
        price:
          type: string
        deepLinks:
          type: array
          items:
            $ref: '#/components/schemas/DeepLink'
      required:
        - price
        - deepLinks
    Segment:
      type: object
      properties:
        id:
          type: string
        from:
          type: string
        to:
          type: string
        duration:
          type: number
        departure:
          type: string
        arrival:
          type: string
      required:
        - id
        - from
        - to
        - duration
        - departure
        - arrival
    Leg:
      type: object
      properties:
        id:
          type: string
        from:
          type: string
        to:
          type: string
        duration:
          type: number
        departure:
          type: string
        arrival:
          type: string
        stops:
          type: number
        segments:
          type: array
          items:
            $ref: '#/components/schemas/Segment'
      required:
        - id
        - from
        - to
        - duration
        - departure
        - arrival
        - stops
        - segments
    Flight:
      type: object
      properties:
        itineraryId:
          type: string
        deals:
          type: array
          items:
            $ref: '#/components/schemas/Deal'
        price:
          type: string
        deepLink:
          type: string
        legs:
          type: array
          items:
            $ref: '#/components/schemas/Leg'
      required:
        - itineraryId
        - deals
        - price
        - deepLink
        - legs
    Stats:
      type: object
      properties:
        total:
          type: number
        minPrice:
          type: string
      required:
        - total
        - minPrice
    Search:
      type: object
      properties:
        sessionToken:
          type: string
        best:
          type: array
          items:
            $ref: '#/components/schemas/Flight'
        cheapest:
          type: array
          items:
            $ref: '#/components/schemas/Flight'
        fastest:
          type: array
          items:
            $ref: '#/components/schemas/Flight'
        stats:
          $ref: '#/components/schemas/Stats'
      required:
        - sessionToken
        - best
        - cheapest
        - fastest
        - stats